# Generated by Django 5.2.6 on 2025-11-25 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0005_recommendation_userevent_viewedproduct'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product_details',
            name='category',
            field=models.CharField(choices=[('gold', 'Gold'), ('silver', 'Silver'), ('diamond', 'Diamond'), ('traditional', 'Traditional'), ('fashion', 'Fashion')], default='fashion', max_length=50),
        ),
        migrations.AlterField(
            model_name='product_details',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='OutfitUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outfit_image', models.ImageField(upload_to='outfits/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OutfitRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=200)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.product_details')),
                ('outfit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='app2.outfitupload')),
            ],
        ),
    ]
