# Generated by Django 5.2.6 on 2025-11-20 16:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0006_alter_gallery_options_gallery_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_datetime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
