# Generated by Django 5.2.6 on 2025-11-20 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0007_mymodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gallery',
            new_name='Gall',
        ),
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
